// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR0Gv9LVrzmbXF_VEdxyVrdMaq8OTpMt8',
    appId: '1:34554848898:web:5b7e4c7161b98da3f9369b',
    messagingSenderId: '34554848898',
    projectId: 'testtask-13962',
    authDomain: 'testtask-13962.firebaseapp.com',
    storageBucket: 'testtask-13962.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN0bp507QKt18ioDzc4WihfvuWFqD2Hdc',
    appId: '1:34554848898:android:c44894f14825e9e9f9369b',
    messagingSenderId: '34554848898',
    projectId: 'testtask-13962',
    storageBucket: 'testtask-13962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTiT0J7UHrv2zvPCkaQP60A9MjC6CLF4',
    appId: '1:34554848898:ios:aff77f593bb38058f9369b',
    messagingSenderId: '34554848898',
    projectId: 'testtask-13962',
    storageBucket: 'testtask-13962.firebasestorage.app',
    iosClientId: '34554848898-ebkg568asjp7vjbu11s5vbm8ffjdqu0m.apps.googleusercontent.com',
    iosBundleId: 'com.kudldz.naiem.ambit.mylab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTiT0J7UHrv2zvPCkaQP60A9MjC6CLF4',
    appId: '1:34554848898:ios:aff77f593bb38058f9369b',
    messagingSenderId: '34554848898',
    projectId: 'testtask-13962',
    storageBucket: 'testtask-13962.firebasestorage.app',
    iosClientId: '34554848898-ebkg568asjp7vjbu11s5vbm8ffjdqu0m.apps.googleusercontent.com',
    iosBundleId: 'com.kudldz.naiem.ambit.mylab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR0Gv9LVrzmbXF_VEdxyVrdMaq8OTpMt8',
    appId: '1:34554848898:web:9f2a48cba1b3b9aaf9369b',
    messagingSenderId: '34554848898',
    projectId: 'testtask-13962',
    authDomain: 'testtask-13962.firebaseapp.com',
    storageBucket: 'testtask-13962.firebasestorage.app',
  );

}